<?
  $this->headTitle($this->translate('MyResearch Help'));

  try { // language missing
    echo $this->partial($this->tpl_lang);
  } catch(Exception $e) {
    try { // for missing file error message
      $this->partial($this->tpl_en); // existence check
      ?><p class="warning"><?=$this->transEsc('Sorry, but the help you requested is unavailable in your language.') ?></p><?
      echo $this->partial($this->tpl_en);
    } catch(Exception $e) {
      $this->layout->setLayout('layout');
      throw new Exception('Unknown Help Page');
    }
  }
?>