<div class="footer-text"><a href="#" class="standard-view" rel="external"><?=$this->transEsc('Go to Standard View')?></a></div>

<div data-role="footer" data-theme="b">
  <?
    // if a module has footer-navbar.tpl, then use it, otherwise use default
    try {
        echo $this->partial("{$this->controller}/footer-navbar.phtml", $this);
    } catch (Zend_View_Exception $e) {
        // no module-specific footer navbar found -- use default.
        echo $this->partial('default-footer-navbar.phtml', $this);
    }
  ?>
</div>
