<div data-role="header" data-theme="b">
  <h1><? foreach ($this->headTitle() as $str) echo trim($str, ':/') . ' '; ?></h1>

  <? if (!(isset($this->hideSearchLink) && $this->hideSearchLink)): ?>
    <a rel="external" href="<?=$this->url(array('controller' => 'Search', 'action' => 'Home'), 'default', true)?>" data-icon="search"  class="ui-btn-right">
      <?=$this->transEsc('Search')?>
    </a>
  <? endif; ?>

  <?
    // if a module has header-navbar.tpl, then use it
    try {
        echo $this->partial("{$this->controller}/header-navbar.phtml", $this);
    } catch (Zend_View_Exception $e) {
        // no header navbar found -- do nothing.
    }
  ?>
</div>
