<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - Home'));

    // Set up map of core name => label
    $coreLabels = array(
        'biblio' => $this->translate('Bibliographic Index'),
        'authority' => $this->translate('Authority Index'),
        'stats' => $this->translate('Usage Statistics Index')
    );
?>
<div class="span-5">
  <?=$this->partial("admin/menu.phtml", array('action' => $this->action))?>
</div>

<div class="span-18 last">
  <h1><?=$this->transEsc('VuFind Administration')?></h1>

  <? $cores = is_object($this->xml) ? $this->xml->xpath('/response/lst[@name="status"]/lst') : array(); ?>
  <? foreach ($cores as $core): ?>
    <? $coreName = (string)$core['name']; ?>
    <? $coreLabel = isset($coreLabels[$coreName]) ? $coreLabels[$coreName] : ucwords($coreName) . ' Index'; ?>
    <h2><?=$this->transEsc($coreLabel)?></h2>
    <table class="citation">
      <tr>
        <th><?=$this->transEsc('Record Count')?>: </th>
        <td><?=$this->escape((string)array_pop($core->xpath('//lst[@name="' . $coreName . '"]/lst/int[@name="numDocs"]')))?></td>
      </tr>
      <tr>
        <th><?=$this->transEsc('Start Time')?>: </th>
        <td><?=$this->escape(strftime("%b %d, %Y %l:%M:%S%p", strtotime((string)array_pop($core->xpath('//lst[@name="' . $coreName . '"]/date[@name="startTime"]')))))?></td>
      </tr>
      <tr>
        <th><?=$this->transEsc('Last Modified')?>: </th>
        <td><?=$this->escape(strftime("%b %d, %Y %l:%M:%S%p", strtotime((string)array_pop($core->xpath('//lst[@name="' . $coreName . '"]/lst/date[@name="lastModified"]')))))?></td>
      </tr>
      <tr>
        <th><?=$this->transEsc('Uptime')?>: </th>
        <td><?=$this->printms((string)array_pop($core->xpath('//lst[@name="' . $coreName . '"]/long[@name="uptime"]')))?></td>
      </tr>
    </table>
  <? endforeach; ?>
</div>

<div class="clear"></div>
