<?
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('Upgrade VuFind') . '</em>';
?>
<h1><?=$this->transEsc('Upgrade VuFind')?></h1>
<?=$this->flashmessages()?>
<p>We cannot upgrade VuFind at this time.  You can try <a href="<?=$this->url(array('controller' => 'Upgrade', 'action' => 'Reset'), 'default', true)?>">starting over</a>.</p>