<?
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('Upgrade VuFind') . '</em>';
?>
<h1><?=$this->transEsc('Upgrade VuFind')?></h1>
<?=$this->flashmessages()?>

<p>Some of the items in your resource table appear to be missing metadata.  Adding this metadata may take some time,
but it will improve the user experience by allowing proper sorting of favorites and tagged records.</p>

<br />

<form method="POST" action="<?=$this->url(array('controller' => 'Upgrade', 'action' => 'FixMetadata'), 'default', true)?>">
  <input type="submit" name="submit" value="Yes, fix the metadata; I'll wait." /><br /><br />
  <input type="submit" name="skip" value="Do not fix the metadata at this time." onclick="return confirm('Are you sure you want to skip this step?');"/>
</form>