<? if (!empty($this->authors)): ?><?=$this->escape($this->authors)?>. <? endif; ?>
&quot;<?=$this->title?><? if ($this->periodAfterTitle): ?>.<? endif ?>&quot; 
<span style="font-style:italic;"><?=$this->escape($this->journal)?></span> 
<? if (!empty($this->numberAndDate)): ?><?=$this->escape($this->numberAndDate)?>: <? endif; ?>
<? if (!empty($this->pageRange)): ?><?=$this->escape($this->pageRange)?><? endif; ?>.
